"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(dotenv_path=BASE_DIR.parent / ".env", override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# 임베딩(semantic search)용 모델
GEMINI_EMBED_MODEL = "text-embedding-004"

# 추천 요청 시 임베딩이 없는 책을 'lazy'로 생성해주는 최대 개수(과도한 API 호출 방지)
AI_EMBED_LAZY_LIMIT = int(os.getenv("AI_EMBED_LAZY_LIMIT", "10"))

# 임베딩에 넣을 텍스트 최대 길이(너무 길면 400 잘 남)
AI_MAX_EMBED_CHARS = int(os.getenv("AI_MAX_EMBED_CHARS", "2500"))

# title 최대 길이
AI_MAX_EMBED_TITLE_CHARS = int(os.getenv("AI_MAX_EMBED_TITLE_CHARS", "120"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t8=ook9j-uzm*e&pzxo+3on1&c*yo*pg^dn6g7j^k%kw*(tl2_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "corsheaders",  # CORS 처리를 위해 필수
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # local
    "accounts",
    "books",
    "interactions",
    "ai",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,  # refresh 재발급 시 기존 토큰 폐기
    "BLACKLIST_AFTER_ROTATION": True,  # 폐기된 refresh를 blacklist에 등록
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # [중요] 최상단 위치 유지
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ==============================================================================
# [수정] CORS 설정 (에러가 발생한 v1 주소 추가)
# ==============================================================================
# 개발 중에는 True로 해도 되지만, 배포 시에는 명시하는 것이 좋습니다.
# CORS_ALLOW_ALL_ORIGINS = True 

CORS_ALLOWED_ORIGINS = [
    "https://ungseongx2v1.netlify.app",        # [현재 에러 발생 주소]
    "https://ungseongx2v2.netlify.app",        # [이전 주소] (혹시 몰라 유지)
    "http://localhost:5173",                   # [로컬 테스트용]
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# ==============================================================================
# [수정] CSRF 신뢰 도메인 설정 (백엔드 주소도 에러 로그에 맞춰 수정)
# ==============================================================================
CSRF_TRUSTED_ORIGINS = [
    "https://ungseongx2v1.netlify.app",        # [현재 프론트엔드]
    "https://ungseongx2v2.netlify.app",        # [이전 프론트엔드]
    "https://unseongx2.up.railway.app",        # [현재 에러 로그의 백엔드 주소]
    "https://pjtv2-production.up.railway.app", # [이전 백엔드 주소]
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 로컬 테스트용 (필요시 주석 해제)
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    # 배포용 (Railway)
    "default": dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}', conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 슬래시가 없는 URL로 요청이 와도 자동으로 슬래시를 붙여서 처리하도록 유도
APPEND_SLASH = True
