"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

from dotenv import load_dotenv # dotenv 임포트

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# [수정] .env 파일 경로 설정 (1번 상황: backend 폴더 내부에 있을 때)
# BASE_DIR이 곧 backend 폴더를 가리킵니다.
env_path = BASE_DIR / ".env"

# .env 파일 로드 시도
if env_path.exists():
    print(f"✅ .env 파일을 찾았습니다: {env_path}")
    load_dotenv(dotenv_path=env_path, override=True)
else:
    print(f"⚠️ .env 파일을 찾을 수 없습니다: {env_path}")
    # 혹시 몰라 상위 폴더도 한 번 찾아보는 예비 코드 (필요 없으면 무시됨)
    load_dotenv(dotenv_path=BASE_DIR.parent / ".env", override=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# [확인용] 서버 켜질 때 키가 제대로 들어왔는지 콘솔에 출력
if GEMINI_API_KEY:
    print(f"🔑 API Key 로드 성공 (앞 5자리): {GEMINI_API_KEY[:5]}...")
else:
    print("🔥 [경고] GEMINI_API_KEY가 없습니다! .env 파일 내용을 확인하세요.")

# 임베딩(semantic search)용 모델
GEMINI_EMBED_MODEL = "text-embedding-004"

# 추천 요청 시 임베딩이 없는 책을 'lazy'로 생성해주는 최대 개수(과도한 API 호출 방지)
AI_EMBED_LAZY_LIMIT = int(os.getenv("AI_EMBED_LAZY_LIMIT", "10"))

# 임베딩에 넣을 텍스트 최대 길이(너무 길면 400 잘 남)
AI_MAX_EMBED_CHARS = int(os.getenv("AI_MAX_EMBED_CHARS", "2500"))

# title 최대 길이
AI_MAX_EMBED_TITLE_CHARS = int(os.getenv("AI_MAX_EMBED_TITLE_CHARS", "120"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t8=ook9j-uzm*e&pzxo+3on1&c*yo*pg^dn6g7j^k%kw*(tl2_"

# SECURITY WARNING: don't run with debug turned on in production!
# 서버 배포가 진행중이면 True -> False로 수정!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # local
    "accounts",
    "books",
    "interactions",
    "ai",
]

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,  # refresh 재발급 시 기존 토큰 폐기
    "BLACKLIST_AFTER_ROTATION": True,  # 폐기된 refresh를 blacklist에 등록
    "AUTH_HEADER_TYPES": ("Bearer",),
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True  # 개발용
# 또는 CORS_ALLOWED_ORIGINS = ["http://localhost:5173", ...]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

CSRF_TRUSTED_ORIGINS = [
    "https://candid-manatee-f4b3ab.netlify.app",
    "https://pjt-library-production.up.railway.app",
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    # 원격 서버로 운용할꺼면 위를 주석하고 아래를 주석해제
    "default": dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}', conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 슬래시가 없는 URL로 요청이 와도 자동으로 슬래시를 붙여서 처리하도록 유도
APPEND_SLASH = True

# 이 설정이 있어야 'media/comics' 폴더에 이미지가 저장됩니다.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
