# Generated by Django 5.2.9 on 2025-12-23 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('books', '0002_rename_isbn_book_isbn13'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='airecommendation',
            old_name='recommended_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='recommended_list',
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.airecommendation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recommendation', 'book'), name='uniq_reco_book')],
            },
        ),
    ]
