# Generated by Django 5.2.9 on 2025-12-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_recommended_at_airecommendation_created_at_and_more'),
        ('books', '0002_rename_isbn_book_isbn13'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_norm', models.FloatField(blank=True, null=True)),
                ('embedding_model', models.CharField(default='gemini-embedding-001', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_embedding', to='books.book')),
            ],
        ),
    ]
